apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin
  namespace: distribuidos  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zipkin
  template:
    metadata:
      labels:
        app: zipkin
    spec:
      containers:
      - name: zipkin
        image: openzipkin/zipkin:latest # Cambia a tu imagen y etiqueta específicas
        ports:
        - containerPort: 9411